# Generated by Django 4.0.4 on 2022-06-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0003_entregable_remove_curso_fechadeentrega_curso_camada_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Alumno',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='profesion',
        ),
    ]
