# Generated by Django 4.0.4 on 2022-06-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0004_rename_estudiantes_alumno_delete_entregable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='email',
        ),
        migrations.AddField(
            model_name='profesor',
            name='legajo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
